name: flutter_bloc_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.3.0
  get_it: ^8.0.3
  go_router: ^16.0.0
  mobx: ^2.5.0
  flutter_screenutil: ^5.9.3

dev_dependencies:
  build_runner: ^2.5.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mobx_codegen: ^2.7.1

flutter:
  uses-material-design: true
  generate: true
